loading:
  ##@param method - string - required
  #method to load the data into datawarehouse (full/incremental)
  #default: incremental
  #NOTE: full loading will delete data in the existing DB (backup the data if necessary)
  method: incremental
  #method: full
  
  ##@param day_update_lag - numeric - required
  #Number of days between today and the latest data to be extracted and loaded into the Datawarehouse (0: today's data, 1: yesterday's)
  #default: 2 days
  #NOTE: if the value is negative, system will use the default value (2 days)
  day_update_lag: 2
  
  ##@param start_date_full_load - date (yyyy-mm-dd) - optional
  #The earliest data to be extracted and loaded into the Datawarehouse 
  start_date_full_load: 2010-01-01
  
  ##@param default_full_load_month - numeric - required
  # Number of months to monitor a campaign email actions
  default_full_load_month: 1

  ##@param days - numeric - required
  # Number of days - 30 * default_full_load_month
  campaign_active_period_length: 10
  
  
  